version: '3.8'
services:
  prestamos-service:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: reportes-service
    ports:
      - "8082:8082"
    env_file:
      - ../.env

    networks:
      - backend

networks:
  backend:
    driver: bridge